# Generated by Django 5.2.4 on 2025-08-21 19:50

import appointments.mixin_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Not specified'), ('pending', 'Pending'), ('confirmed_by_recipients', 'Confirmed by Recipients'), ('canceled_by_recipients', 'Canceled by Recipients'), ('canceled_by_providers', 'Canceled by Providers'), ('completed', 'Completed'), ('no_show', 'No-show')], default='pending', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('auto_price', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True)),
                ('auto_end_time', models.BooleanField(default=True)),
                ('prevents_overlap', models.BooleanField(default=True)),
            ],
            bases=(models.Model, appointments.mixin_models.AppointmentValidateMixin),
        ),
        migrations.CreateModel(
            name='AppointmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
            bases=(models.Model, appointments.mixin_models.ActivityMixin),
        ),
        migrations.AddField(
            model_name='appointment',
            name='activities',
            field=models.ManyToManyField(related_name='appointments_as_activities', through='appointments.AppointmentActivity', to='activities.activity'),
        ),
        migrations.CreateModel(
            name='AppointmentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, appointments.mixin_models.ProviderValidateMixin),
        ),
        migrations.AddField(
            model_name='appointment',
            name='providers',
            field=models.ManyToManyField(related_name='appointments_as_provider', through='appointments.AppointmentProvider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AppointmentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='recipients',
            field=models.ManyToManyField(related_name='appointments_as_recipient', through='appointments.AppointmentRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appointmentactivity',
            index=models.Index(fields=['activity', 'appointment'], name='appointment_activit_6c70a3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentprovider',
            index=models.Index(fields=['provider', 'appointment'], name='appointment_provide_60d9c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentprovider',
            constraint=models.UniqueConstraint(fields=('appointment', 'provider'), name='unique_appointment_provider'),
        ),
        migrations.AddIndex(
            model_name='appointmentrecipient',
            index=models.Index(fields=['recipient', 'appointment'], name='appointment_recipie_04150e_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrecipient',
            constraint=models.UniqueConstraint(fields=('appointment', 'recipient'), name='unique_appointment_recipient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='appointment_date_85c852_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_blocked'], name='appointment_is_bloc_d8ab94_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'start_time'], name='appointment_date_85ff09_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'end_time'], name='appointment_date_48e97a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='appointment_date_f71b0d_idx'),
        ),
    ]
